// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx("div", {
                          children: JsxRuntime.jsx("h1", {
                                children: "Passsword Generator",
                                className: "text-maindark text-3xl font-semibold"
                              }),
                          className: "p-6"
                        })
                  }),
              className: "screen-container"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
