// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "What is this about?",
                    className: "text-3xl font-semibold"
                  }),
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
